DROP TABLE ESPECIALCUIDADO;
DROP TABLE ESPECIAL;
DROP TABLE PESSOAHABILIDADE;
DROP TABLE AULAPESSOA;
DROP SEQUENCE CONTADORESPECIAL;

CREATE TABLE AULAPESSOA(
  CPF NUMBER(11) PRIMARY KEY,
  NOME VARCHAR(50)
);

CREATE TABLE PESSOAHABILIDADE(
  CPF NUMBER(11),
  HABILIDADE VARCHAR(50),
  CONSTRAINT PKPH PRIMARY KEY (CPF,HABILIDADE),
  CONSTRAINT FKPH FOREIGN KEY (CPF) REFERENCES AULAPESSOA(CPF)
);

CREATE TABLE ESPECIAL(
  NROESPECIAL INTEGER PRIMARY KEY,
  CPFESPECIAL NUMBER(11),
  CPFSUPERVISOR NUMBER(11),
  APELIDO VARCHAR(50) DEFAULT 'NENHUM',
  CONSTRAINT FKE1 FOREIGN KEY (CPFESPECIAL) REFERENCES AULAPESSOA(CPF) ON DELETE CASCADE,
  CONSTRAINT FKE2 FOREIGN KEY (CPFSUPERVISOR) REFERENCES AULAPESSOA(CPF) ON DELETE SET NULL
);

CREATE TABLE ESPECIALCUIDADO(
  NROESPECIAL INTEGER,
  CUIDADO VARCHAR(50),
  CONSTRAINT FKEC FOREIGN KEY (NROESPECIAL) REFERENCES ESPECIAL(NROESPECIAL) ON DELETE CASCADE,
  CONSTRAINT PKEC PRIMARY KEY (NROESPECIAL,CUIDADO)
);

INSERT INTO AULAPESSOA(CPF, NOME) VALUES ('1111',ANA);
INSERT INTO AULAPESSOA(CPF,NOME) VALUES ('2222',BRUNO);
INSERT INTO AULAPESSOA(CPF,NOME) VALUES('3333',CAMILA);
INSERT INTO AULAPESSOA(CPF,NOME) VALUES('4444',DANIEL);
INSERT INTO AULAPESSOA(CPF,NOME) VALUES('5555',ERICA);

INSERT INTO PESSOAHABILIDADE(CPF,HABILIDADE) VALUES ('1111','ATENCAO LONGA');
INSERT INTO PESSOAHABILIDADE(CPF,HABILIDADE) VALUES ('1111', 'PACIENCIA');
INSERT INTO PESSOAHABILIDADE(CPF,HABILIDADE) VALUES ('1111', 'HONESTIDADE');
INSERT INTO PESSOAHABILIDADE(CPF,HABILIDADE) VALUES ('2222','FORCA');
INSERT INTO PESSOAHABILIDADE(CPF,HABILIDADE) VALUES ('2222','CALMA');
INSERT INTO PESSOAHABILIDADE(CPF,HABILIDADE) VALUES ('2222','CORAGEM');
INSERT INTO PESSOAHABILIDADE(CPF,HABILIDADE) VALUES ('3333','ATENCAO LONGA');
INSERT INTO PESSOAHABILIDADE(CPF,HABILIDADE) VALUES ('3333','PACIENCIA');
INSERT INTO PESSOAHABILIDADE(CPF,HABILIDADE) VALUES ('3333','HONESTIDADE');
INSERT INTO PESSOAHABILIDADE(CPF,HABILIDADE) VALUES ('3333','EMPATIA');





